theme: minima
title: zomzones blog
author: Thomas Jones
description: This is a personal blog for Thomas Jones (zomzones) to showcase and document progress on projects such as my biotech sales news tool. 
